# Generated by Django 3.0.8 on 2020-07-21 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='作业', max_length=50, verbose_name='标题')),
                ('content', models.FileField(default='无', upload_to='', verbose_name='作业')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_reviewed', models.BooleanField(default=False, max_length=10, verbose_name='批改')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('credit', models.IntegerField(default=0, verbose_name='获得学分')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type.Type', verbose_name='科目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
