# Generated by Django 3.0.8 on 2020-07-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='content',
            field=models.FileField(default='无', upload_to='assign/', verbose_name='作业'),
        ),
    ]
