# Generated by Django 3.0.8 on 2020-07-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20200723_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='content',
            field=models.FileField(upload_to='assign/', verbose_name='作业'),
        ),
    ]
