# Generated by Django 3.0.8 on 2020-07-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(default='暂无信息', max_length=10, verbose_name='角色')),
            ],
        ),
    ]
