# Generated by Django 3.0.8 on 2020-07-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='credit',
            field=models.IntegerField(default=0, verbose_name='学分'),
        ),
    ]
